# config/schedule.yml

register_webhooks:
  cron: "every day at 5"
  class: "TiiRegisterWebHookJob"

progress_turn_it_in_jobs:
  cron: "every 30 minutes"
  class: "TiiCheckProgressJob"

clean_read_receipts_job:
  cron: "every day at 4"
  class: "CleanReadReceiptsJob"
